apiVersion: v1
kind: Pod
metadata:
  name: labels
  labels:
    project: roboshop
    components: mysql
    tier: backend
    environment: dev
  annotations:
    description: "this pod is created to demonstrate pod annotations"
    jenkins: "https://jenkins.com/build/jobs/roboshop-catalogue/3"
spec:    
  containers:
  - name: nginx
    image: nginx  
      