apiVersion: v1
kind: Pod
metadata:
  name: labels
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests: #soft limit
        memory: "64Mi"
        cpu: "250m"
      limits: #hard limit
        memory: "128Mi"
        cpu: "150m"