apiVersion: v1
kind: Pod
metadata:
  name: env-demo
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: COURSE
      value: "KUBERNETS"
    - name: "TRAINER" 
      value: "SIVA" 