apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    purpose: service-demo
spec:
  selector:


---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels: 
    purpose: demo
spec: 
  containers: 
  - name: nginx
    image: nginx    