apiVersion: v1
kind: Service
metadata:
  name: sc-headless-svc
  labels:
    purpose: statefulset
    project: roboshop
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    purpose: statefulset
    project: roboshop
---
apiVersion: v1
kind: Service
metadata:
  name: sc-normal-svc
  labels:
    purpose: statefulset
    project: roboshop
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    name: web
  selector:
    purpose: statefulset
    project: roboshop
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sc-headless
spec:
  serviceName: sc-headless-svc
  replicas: 3
  selector:
    matchLabels:
      purpose: statefulset
      project: roboshop
  template:
    metadata:
      labels:
        purpose: statefulset
        project: roboshop
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: efs-roboshop
      resources:
        requests:
          storage: 2Gi